AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  voters

  AWS Lambda that manages a set of voters

Globals:
  Function:
    Timeout: 15
    MemorySize: 512
    Tracing: Active
    Runtime: java11
    Environment: 
        Variables:
            JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1    

Resources:     
    ListVotersFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: me.weatherill.will.voters.App::handleRequest
            CodeUri: VotersFunction
            Events:
                ListAllApi:
                    Type: Api
                    Properties:
                        Path: /voters
                        Method: GET      
            
Outputs:
  VotersApi:
    Description: "API Gateway endpoint URL for Prod stage for Voters function"
    Value: !Sub "https://${VotersAPI}.execute-api.${AWS::Region}.amazonaws.com/prod/voters/" 
  
  ListVotersFunction:
    Description: "Voters Lambda Function ARN"
    Value: !GetAtt ListVotersFunction.Arn
  
  ListVotersFunctionIamRole:
    Description: "Implicit IAM Role created for List Voters function"
    Value: !GetAtt ListVotersFunctionRole.Arn